lang: en
memory_manager:
    manger: postgres
    # manger: memofile
    minimum_similarity: 0.75
    maximum_context_return: 1
    chunk_size: 350
    chunk_overlap: 10
server_manager:
  host: 0.0.0.0
  port: 8000
  cors:
    allow_origins:
      - "*"
    allow_origin_regex: None
    allow_credentials: True
    allow_methods:
      - "GET"
      - "POST"
    allow_headers:
      - "*"
    max_age:
      - 600
model_manager:
  chat_model:
    # model_path: res/model/DeepSeek-R1-Distill-Qwen-7B-Q4_K_M.gguf
    models_path: sneak-service/res/model/
    default_model: NeuralQwen-2.5-1.5B-Spanish.Q4_K_M.gguf
    n_gpu_layers: -1
    n_threads: 8
    max_tokens: -1
    streaming: True
    n_ctx: 4096

  embedding_model:
    models_path: sneak-service/res/model/
    default_model: nomic-embed-text-v1.5.Q4_K_M.gguf
    n_gpu_layers: -1
    n_threads: 8
    max_tokens: -1
    n_ctx: 4096
initial_prompt: Eres un abogado laboral español el cual debe ayudar de forma gentil y concisa a su cliente. Si desconoces la respuesta o no tienes contexto simplemente no respondas